name: Daily Commit Workflow

on:
  schedule:
    # Run daily at 12:00 PM UTC (adjust the cron syntax for your desired time)
    - cron: '0 12 * * *'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add a commit with email 21f3002277@ds.study.iitm.ac.in
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "21f3002277@ds.study.iitm.ac.in"
          date > timestamp.txt
          git add timestamp.txt
          git commit -m "Daily automated commit by GitHub Actions"
          git push
